### ISSUE TITLE
If rhsm.conf is missing but /etc/rhsm-host directory exists, repo_ca_cert gets set to a bogus value: /etc/rhsm-host-host/ca/redhat-uep.pem

### ISSUE THREAD

**Issue by yrro** [rpm-software-management/librhsm#9] opened 2023-02-10 13:46 UTC
If running inside a container and `/etc/rhsm-host/rhsm.conf` does not exist (as on RHCOS where `/etc/rhsm` does not contain the usual config files, only the `ca` directory) then:

1. `rhsm_context_new ` is called, it checks for `/etc/rhsm-host`
2. `/etc/rhsm-host` exists so `in_container` is true
3. `conf_dir ` is set to `/etc/rhsm-host`.
4. `g_key_file_load_from_file ` tries to read `/etc/rhsm-host/rhsm.conf` which does not exist, so it returns null.
  It would be helpful if a warning could be emittedin this case.
5. `rhsm_context_new` calls `g_object_new` specifying `conf-file` as `/etc/rhsm-host/rhsm.conf` and the other five properties (which would have been read from the config file if it existed), including `repo-ca-cert` as null.
6. GObject calls `rhsm_context_constructed`
7. `rhsm_context_constructed` checks each of the properties and upon seeing they are null, provides default values.
8. `repo_ca_cert` gets defaulted to g_build_filename(g_build_filename(dirname("/etc/rhsm-host/rhsm.conf"), "ca"), "redhat-uep.pem") i.e., `/etc/rhsm-host/ca/redhat-uep.pem`
9. Before `rhsm_context_constructed` returns, [it checks](https://github.com/rpm-software-management/librhsm/blob/5e0674cf389f14174208641ec411ba7be448d5e3/rhsm/rhsm-context.c#L541) if `ctx->conf_file` starts with `CONFIG_DIR_HOST`, i.e., `/etc/rhsm-host`; it does.
10. `rhsm_utils_str_replace ` is called to modify the value of `ctx->repo_ca_cert`. It replaces any instances of `/etc/rhsm` with `/ec/rhsm-host`. Before this happens, the value of `repo_ca_cert` was `/etc/rhsm-host/ca/redhat-uep.pem`. Therefore the value of `repo_ca_cert` is changed to `/etc/rhsm-host-host/ca/redhat-uep.pem`.

As a result, if you try to use `microdnf` inside a container running on RHCOS, you get:

```
STEP 7/9: RUN microdnf -y install ipa-client
Downloading metadata...
Downloading metadata...
Downloading metadata...
Downloading metadata...
error: cannot update repo 'rhel-8-for-x86_64-baseos-rpms': Cannot download repomd.xml: Curl error (77): Problem with the SSL CA cert (path? access rights?) for https://cdn.redhat.com/content/dist/rhel8/8/x86_64/baseos/os/repodata/repomd.xml [error setting certificate verify locations:
  CAfile: /etc/rhsm-host-host/ca/redhat-uep.pem
  CApath: none]; Last error: Curl error (77): Problem with the SSL CA cert (path? access rights?) for https://cdn.redhat.com/content/dist/rhel8/8/x86_64/baseos/os/repodata/repomd.xml [error setting certificate verify locations:
  CAfile: /etc/rhsm-host-host/ca/redhat-uep.pem
  CApath: none]
error: build error: error building at STEP "RUN microdnf -y install ipa-client": error while running runtime: exit status 1
```

**Comment by j-mracek** [comment] 2023-02-13 15:26
I think that the issue is related to https://bugzilla.redhat.com/show_bug.cgi?id=2143946 that was closed as wontfix

**Comment by yrro** [comment] 2023-02-17 11:45
I think that's a separate issue. On RHCOS (OpenShift), there is no `rhsm.conf` file from the base OS; `/etc/rhsm-host/rhsm.conf` does not exist. As a result the untested combination of variables causes the behaviour that `microdnf` looks for the non-existing `/etc/rhsm-host-host/ca/redhat-uep.pem` file instead of the expected `/etc/rhsm-host/ca/redhat-uep.pem` file.

The `rhsm_utils_str_replace` calls are made so that the paths in `/etc/rhsm-host/rhsm.conf` (which refer to files in `/etc/rhsm` are fixed up to refer to files in `/etc/rhsm-host` instead. But on RHCOS (or in any other case where `/etc/rhsm-host` exists but `/etc/rhsm-host/rhsm.conf` does not exist), the fixup should not take place, because it's not necessary, as the default values for file paths provided by `rhsm_context_constructed` are constructed starting with `/etc/rhsm-host` already.

The impact of this is that it has made debugging issues with entitled builds on OpenShift of images based on `ubi-minimal` significantly more time consuming, as we had to figure out why `microdnf` was complaining about files within the totally bogus `/etc/rhsm-host-host` directory.

**Comment by ppisar** [comment] 2023-10-27 10:50
This is indeed a bug. An intention of the questioned code is to relocate ctx->ca_cert_dir and ctx->repo_ca_cert from /etc/rhsm/ to /etc/rhsm-host/ if ctx->conf_file is located in /etc/rhsm-host/. A mistake in the code is that "/etc/rhsm" is a prefix of "/etc/rhsm-host" and thus if the relocated path already starts with "/etc/rhsm-host/", it is mangled into "/etc/rhsm-host-host/" instead of kept intact "/etc/rhsm-host/...".

Another bug is that the code checks for a string prefix ("/etc/rhsm-host") instead for a path prefix ("/etc/rhsm-host/"). As a result paths like "/etc/rhsm-hostFOO" is also mishandled.

**Comment by j-mracek** [comment] 2023-10-27 11:26
I also think that it is a bug. The another question is whether we can back-port the patch to RHEL8/9.

**Comment by ppisar** [comment] 2023-10-27 11:52
That's a question for RHEL <https://issues.redhat.com/browse/RHEL-14224>. Not for this upstream project.

**Closed as completed** 2023-11-08 06:57 UTC
Labels: triaged
